Feat/unit test
CottaCush/AndroidCommons pull request #8
Opened 2017-11-24 07:39 UTC by R4SH33D

2017-11-24 14:07 UTC, goke-epapa requested changes
Try to test for both failure case and success case.

2017-11-24 14:07 UTC, goke-epapa commented on README.md
> +[![Build Status](https://travis-ci.org/CottaCush/AndroidCommons.svg?branch=feat%2Funit_test)](https://travis-ci.org/CottaCush/AndroidCommons)
Change branch to master

2017-11-24 14:07 UTC, goke-epapa commented on README.md
> +[![codecov](https://codecov.io/gh/CottaCush/AndroidCommons/branch/feat%2Funit_test/graph/badge.svg)](https://codecov.io/gh/CottaCush/AndroidCommons)
Change branch to `master`

2017-11-24 14:07 UTC, goke-epapa commented on app/src/androidTest/java/com/cottacush/android/libraries/ExampleInstrumentedTest.java
>      public void useAppContext() throws Exception {
This method is redundant now

2017-11-24 14:07 UTC, goke-epapa commented on app/src/androidTest/java/com/cottacush/android/libraries/ExampleInstrumentedTest.java
>      public void useAppContext() throws Exception {
You can assert that context is not null here

2017-11-24 14:24 UTC, R4SH33D commented on README.md
> +[![Build Status](https://travis-ci.org/CottaCush/AndroidCommons.svg?branch=feat%2Funit_test)](https://travis-ci.org/CottaCush/AndroidCommons)
The report label will break if i change it to masters(there are no reports for masters branch yet) . I think we should merge first , the update the masters directly to reflect the changes.

2017-11-27 09:37 UTC, goke-epapa approved these changes

2017-11-27 09:39 UTC, merged